spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/securesync}
    username: ${DB_USERNAME:securesync}
    password: ${DB_PASSWORD:securesync}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

