CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_key VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(80) NOT NULL,
    owner_username VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL,
    current_version INTEGER NOT NULL,
    assigned_reviewer VARCHAR(80),
    latest_summary VARCHAR(2000),
    latest_validation_score DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    change_summary VARCHAR(1000),
    created_by VARCHAR(80) NOT NULL,
    checksum VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_document_versions_document
        FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    actor_username VARCHAR(80) NOT NULL,
    remarks VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_approvals_document
        FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(80) NOT NULL,
    actor_username VARCHAR(80) NOT NULL,
    details VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    type VARCHAR(30) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    read_flag BOOLEAN NOT NULL,
    related_document_id BIGINT,
    due_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_documents_owner ON documents(owner_username);
CREATE INDEX idx_documents_status ON documents(status);
CREATE INDEX idx_document_versions_document ON document_versions(document_id, version_number DESC);
CREATE INDEX idx_approvals_document ON approvals(document_id, created_at DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);
CREATE INDEX idx_notifications_user ON notifications(username, created_at DESC);

