CREATE TABLE distribution_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE distribution_list_members (
    distribution_list_id BIGINT NOT NULL,
    member_email VARCHAR(120) NOT NULL,
    CONSTRAINT fk_distribution_list_members_list FOREIGN KEY (distribution_list_id) REFERENCES distribution_lists(id)
);